eureka:
  instance:
    hostname: ${INSTANCE:localhost}
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info 
info:
  author: Thays Gama
  mail: thays.s.gama@gmail.com
server:
  port: ${PORT:9999}
message: Generic
